feat(questionSetNode): QuestionSetNode edit
maki-math/maki-web-hexo pull request #43
Opened 2022-06-02 06:04 UTC by jiandandaoxingfu

To do:
- Insert questionSet.

2022-06-04 11:01 UTC, suica requested changes

2022-06-04 11:01 UTC, suica commented on src/modules/Questions/QuestionsPage.tsx
> +  const { loading2, run } = useRequest(deleteQuestion, { manual: true });
应该没有叫做loading2的属性吧？

2022-06-04 11:01 UTC, suica commented on src/modules/Questions/QuestionsPage.tsx
> +        window.location.reload();
单页面应用一般不会直接刷新页面，而是通过调用回调，让管数据的父组件重新请求一次数据。

回调函数可以作为QuestionList的参数传进来

2022-06-04 11:01 UTC, suica commented on src/modules/App/App.tsx
> +const hasAuth = (() => {
这个鉴权判断有点问题，之后我们对一下

2022-06-04 12:57 UTC, suica commented on src/modules/Questions/QuestionsPage.tsx
> +  const { loading2, run } = useRequest(deleteQuestion, { manual: true });
`const {loading:loading2} = useRequest(...)`

2022-06-25 12:32 UTC, suica requested changes
现在登录刷新的问题似乎已经在main分支解决了。
只需要使用useAuth把习题集在未登录的时候去掉即可？

2022-06-25 12:32 UTC, suica commented on src/modules/App/App.tsx
> +            onClick={() => !hasAuth && message.error("您没有查看习题集的权限")
好像这里没有叫做hasAuth的变量呀

2022-06-25 12:32 UTC, suica commented on src/modules/App/App.tsx
> +            onClick={() => !hasAuth && message.error("您没有查看习题集的权限")
`src/utils/auth-token.ts` 可以用这里的useAuth

2022-07-02 01:47 UTC, jiandandaoxingfu commented on src/modules/Questions/QuestionsPage.tsx
> +        window.location.reload();
数据增删改后, 我不知道怎么让父组件重新请求数据.

2022-07-02 12:49 UTC, suica commented on src/modules/Questions/QuestionsPage.tsx
>    const { data, loading } = useRequest(api.question.questionList);
`const [count,refresh] = useState(0);`
`const { data, loading } = useRequest(api.question.questionList,{refreshDeps:[count]});`

2022-07-02 12:49 UTC, suica commented on src/modules/Questions/QuestionsPage.tsx
>    const { data, loading } = useRequest(api.question.questionList);
https://ahooks.js.org/hooks/use-request/refresy-deps

`const { data, refresh } = useRequest(() => getUserSchool(userId));`

2022-07-02 12:51 UTC, suica commented on src/modules/Questions/QuestionSetNodeEditingPage.tsx
> +          &nbsp;&nbsp;
不要在代码里写&nbsp;
如果有需要的话可以使用<Space>。有可能需要给Space加上width:100%；

2022-07-03 07:14 UTC, merged