feat(Courses): courses editing
maki-math/maki-web-hexo pull request #46
Opened 2022-07-17 10:30 UTC by jiandandaoxingfu

- CoursesPage页面, courses/edit和courses/edit/:id路由有问题.
- 创建课程怎么和课程类别建立联系.

2022-07-23 08:46 UTC, suica requested changes

2022-07-23 08:46 UTC, suica commented on src/modules/Course/CourseEditingPage.tsx
> +      fallback="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMIAAADDCAYAAADQvc6UAAABRWlDQ1BJQ0MgUHJvZmlsZQAAKJFjYGASSSwoyGFhYGDIzSspCnJ3UoiIjFJgf8LAwSDCIMogwMCcmFxc4BgQ4ANUwgCjUcG3awyMIPqyLsis7PPOq
fallback有没有办法别写到ts文件里，而是单独起一个文件？

2022-07-23 16:15 UTC, suica requested changes

2022-07-23 16:15 UTC, suica commented on src/modules/Content/ContentListPage.tsx
> +      sorter: (a, b) => a.article.author < b.article.author,
author可以不需要排序

2022-07-23 16:15 UTC, suica commented on src/modules/Questions/QuestionsPage.tsx
> +      sorter: (a, b) => a.author < b.author,
antd的sorter是需要返回0 1 -1的那种排序，还是返回true, false的那种排序呀？

2022-07-23 16:15 UTC, suica commented on src/modules/Course/CourseEditingPage.tsx
> +        ))}{' '}
这些{' '}可以删掉吗？

2022-07-23 16:15 UTC, suica commented on src/modules/Course/CourseEditingPage.tsx
> +    // Todo: upload image to OSS.
这块我封装一个函数来做吧

2022-07-24 00:58 UTC, jiandandaoxingfu commented on src/modules/Course/CourseEditingPage.tsx
> +        ))}{' '}
好的

2022-07-24 00:58 UTC, jiandandaoxingfu commented on src/modules/Questions/QuestionsPage.tsx
> +      sorter: (a, b) => a.author < b.author,
是返回布尔值.

2022-07-24 00:58 UTC, jiandandaoxingfu commented on src/modules/Content/ContentListPage.tsx
> +      sorter: (a, b) => a.article.author < b.article.author,
好的

2022-07-24 02:03 UTC, closed without merging