feat(Courses): courses editing
maki-math/maki-web-hexo pull request #48
Opened 2022-07-24 03:47 UTC by jiandandaoxingfu

之前的分支commit老是出错, 没办法commit. 重新创建分支.

2022-07-24 07:16 UTC, suica requested changes

2022-07-24 07:16 UTC, suica commented on src/modules/Course/CourseDetail.tsx
> +              <Link to={path}>编辑课程</Link>
编辑可能需要对无权限的用户隐藏一下入口

2022-07-24 07:18 UTC, suica requested changes

2022-07-24 07:18 UTC, suica commented on src/modules/Questions/QuestionEditingPage.tsx
> +                  {loading ? '上传中' : '上传'}
不需要改文字，只需要给Button传入loading参数就行。它会自动在loading=true的时候disable并加上loading图标动画

2022-07-24 11:37 UTC, jiandandaoxingfu commented on src/modules/Course/CourseDetail.tsx
> +              <Link to={path}>编辑课程</Link>
已修改: 使用user-permissions来鉴权.

2022-07-24 11:38 UTC, jiandandaoxingfu commented on src/modules/Questions/QuestionEditingPage.tsx
> +                  {loading ? '上传中' : '上传'}
已修改

2022-07-30 09:53 UTC, suica approved these changes

2022-07-30 09:54 UTC, merged